# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'MajicData' do

pod 'AFNetworking', '~> 3.1.0'
pod 'JSONModel', '~> 1.7.0'
pod 'pop', '~> 1.0.10'
pod 'Masonry', '~> 1.0.2'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'Toast', '~> 3.1.0'
pod 'IQKeyboardManager', '~> 4.0.9'
pod 'MJRefresh', '~> 3.1.12'
pod 'FMDB', '~> 2.6.2'
pod 'DGActivityIndicatorView', '~> 2.1.1'
pod 'JxbDebugTool', '~> 4.5', :configurations => ['Debug']
pod 'SDWebImage', '~> 3.7.6'


end
